"""empty message

Revision ID: 21f185cc44c4
Revises: 113666884db6
Create Date: 2023-01-19 20:38:22.275771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21f185cc44c4'
down_revision = '113666884db6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submitter', sa.String(length=250), nullable=True))
        batch_op.drop_column('submiter')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submiter', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.drop_column('submitter')

    # ### end Alembic commands ###
